simulator_type: libero
task_suite_name: libero_spatial

total_num_envs: null

auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 240
max_episode_steps: 240 # max episode steps for truncation

use_rel_reward: True
reward_coef: 1.0

# RLinf LiberoEnv specific settings
reset_gripper_open: True
is_eval: False

seed: 0
group_size: 1
use_fixed_reset_state_ids: True
use_ordered_reset_state_ids: False

reward_model:
  enable: False
  endpoint: "http://127.0.0.1:18080/score"
  timeout: 120
  nframes: 16
  max_pixels: 200704 # 256 * 28 * 28
  backend: "qwen2_5_vl_vllm"
  backend_kwargs: {}
  video_fps: 4
  fail_on_request_error: False
  binary_reward: True
  success_threshold: 0.5
  keep_temp_video: False
  temp_video_dir: null

# Indicate the reset state id (related to the task_id and trial_id) want to be specified. (e.g. 
# if set 0, the env always use the task 0 and trial 0 in the libero-spatial suite; 
# if set null, the initial states will be sampled from the whole libero-spatial suite. )
specific_reset_id: null # can be a number or null.

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  camera_heights: 256
  camera_widths: 256
